import React from 'react'
import { Heart, Leaf, Users, Sparkles } from 'lucide-react'
import foundersPhoto from '../assets/mieke-marcel-about.jpg'
import egyptLearningPhoto from '../assets/learning-egypt.jpg'
import certificatePhoto from '../assets/learning-certificates.jpg'

const copy={
 en:{
  title:'Our Story',sub:'Mieke van Lierop & Marcel Croes · Sound & Consciousness Guides',
  openingTitle:'A shared direction',
  opening:'Key of Self Love grew from the paths Mieke and Marcel had already been walking: learning how sound, awareness, nature and genuine attention can help people slow down and reconnect. Their shared idea was not to build a large or impersonal wellness business, but to create experiences they would be proud to guide themselves — thoughtful, welcoming and connected to Aruba.',
  arubaTitle:'Why Aruba matters',
  aruba:'Aruba is more than a setting for the experiences. The coastline, ocean, open landscapes and year-round outdoor life shape how each programme is created. Mieke and Marcel saw an opportunity to let visitors experience the island at a slower pace: not simply moving from one activity to the next, but making time for presence, reflection and a more personal connection with the place they are visiting.',
  miekeTitle:'What Mieke brings',
  mieke:'Mieke brings experience from entrepreneurship, administration, hospitality and business operations, together with continued education in energy sound therapy, singing bowls, tuning forks and other sound- and frequency-based practices. She pays close attention to how people are welcomed and cared for, and to the details that help an experience feel calm, personal and well prepared.',
  marcelTitle:'What Marcel brings',
  marcel:'Marcel brings more than seventeen years of experience in education and personal guidance, including work in both the Netherlands and Aruba. His further development includes sound and resonance, consciousness coaching, nervous-system regulation and transformational facilitation. His background supports a grounded way of explaining, guiding and giving people space to experience things at their own pace.',
  togetherTitle:'Built through learning and experience',
  together:'Both have invested years in professional education, practical experience and international retreats and programmes in the Netherlands, Belgium, Italy and Egypt. Those experiences helped them shape a way of working that combines sound and resonance with nature, hospitality, reflection and real human connection.',
  smallTitle:'Why we keep it small',
  small:'The experiences are intentionally private or small-scale. This makes it possible to listen, adapt the programme where appropriate and give each guest genuine attention. It also fits the way Mieke and Marcel want to work with Aruba’s natural environment: carefully, respectfully and without turning a personal experience into a high-volume activity.',
  purpose:'Through Key of Self Love, Mieke and Marcel want to create experiences that help people step out of the usual rush, reconnect with themselves and engage with Aruba in a more meaningful way.',values:'Our values'
 },
 nl:{
  title:'Ons Verhaal',sub:'Mieke van Lierop & Marcel Croes · Sound & Consciousness Guides',openingTitle:'Een gedeelde richting',opening:'Key of Self Love groeide vanuit de wegen die Mieke en Marcel al bewandelden: leren hoe klank, bewustzijn, natuur en oprechte aandacht mensen kunnen helpen vertragen en opnieuw verbinden. Hun gezamenlijke idee was geen grote of onpersoonlijke welzijnsonderneming, maar ervaringen die zij zelf met overtuiging kunnen begeleiden — zorgvuldig, gastvrij en verbonden met Aruba.',arubaTitle:'Waarom Aruba belangrijk is',aruba:'Aruba is meer dan het decor. De kust, oceaan, open landschappen en het buitenleven vormen mee hoe ieder programma wordt samengesteld. Mieke en Marcel zagen een kans om bezoekers het eiland in een rustiger tempo te laten ervaren, met ruimte voor aanwezigheid, reflectie en een persoonlijkere verbinding met de plek.',miekeTitle:'Wat Mieke meebrengt',mieke:'Mieke combineert ervaring in ondernemerschap, administratie, gastvrijheid en bedrijfsvoering met opleidingen in energetische klanktherapie, klankschalen, stemvorken en andere klank- en frequentiegerichte werkwijzen. Zij heeft veel aandacht voor ontvangst, verzorging en de details die een ervaring rustig, persoonlijk en goed voorbereid laten voelen.',marcelTitle:'Wat Marcel meebrengt',marcel:'Marcel brengt meer dan zeventien jaar ervaring in onderwijs en persoonlijke begeleiding mee, in Nederland en Aruba. Zijn verdere ontwikkeling omvat klank en resonantie, bewustzijnscoaching, regulatie van het zenuwstelsel en transformationele begeleiding. Zijn achtergrond ondersteunt een rustige, heldere manier van begeleiden.',togetherTitle:'Gebouwd op leren en ervaren',together:'Beiden investeerden jarenlang in opleidingen, praktijkervaring en internationale retraites en programma’s in Nederland, België, Italië en Egypte. Daaruit groeide een werkwijze waarin klank en resonantie samenkomen met natuur, gastvrijheid, reflectie en echte menselijke verbinding.',smallTitle:'Waarom we het kleinschalig houden',small:'De ervaringen zijn bewust privé of kleinschalig. Daardoor is er ruimte om te luisteren, het programma waar passend aan te passen en iedere gast oprechte aandacht te geven. Het past ook bij de zorgvuldige en respectvolle manier waarop Mieke en Marcel met Aruba’s natuurlijke omgeving willen werken.',purpose:'Met Key of Self Love willen Mieke en Marcel ervaringen creëren die mensen uit de dagelijkse drukte halen, opnieuw met zichzelf verbinden en Aruba op een betekenisvollere manier laten beleven.',values:'Onze waarden'
 },
 es:{
  title:'Nuestra Historia',sub:'Mieke van Lierop y Marcel Croes · Sound & Consciousness Guides',openingTitle:'Una dirección compartida',opening:'Key of Self Love nació de los caminos que Mieke y Marcel ya recorrían: aprender cómo el sonido, la conciencia, la naturaleza y la atención genuina pueden ayudar a las personas a bajar el ritmo y reconectar. Su idea no era crear un negocio grande e impersonal, sino experiencias cuidadosas, acogedoras y conectadas con Aruba.',arubaTitle:'Por qué Aruba importa',aruba:'Aruba es más que un escenario. La costa, el océano, los paisajes abiertos y la vida al aire libre influyen en cada programa. Mieke y Marcel quieren que los visitantes vivan la isla con más calma, presencia y conexión personal.',miekeTitle:'Lo que aporta Mieke',mieke:'Mieke combina experiencia en emprendimiento, administración y hospitalidad con formación en terapia de sonido energético, cuencos, diapasones y otras prácticas de sonido y frecuencia. Presta especial atención a la bienvenida, el cuidado y los detalles.',marcelTitle:'Lo que aporta Marcel',marcel:'Marcel aporta más de diecisiete años de experiencia en educación y orientación personal en los Países Bajos y Aruba, además de formación en sonido, resonancia, acompañamiento de la conciencia y facilitación transformadora.',togetherTitle:'Creado a través del aprendizaje',together:'Ambos han invertido años en formación, experiencia práctica y retiros internacionales en los Países Bajos, Bélgica, Italia y Egipto. De allí surgió una forma de trabajar que une sonido, naturaleza, hospitalidad, reflexión y conexión humana.',smallTitle:'Por qué trabajamos a pequeña escala',small:'Las experiencias son privadas o para grupos pequeños para poder escuchar, adaptar el programa cuando corresponde y ofrecer atención personal, respetando al mismo tiempo el entorno natural de Aruba.',purpose:'Con Key of Self Love, Mieke y Marcel crean experiencias para salir del ritmo cotidiano, reconectar y vivir Aruba de una manera más significativa.',values:'Nuestros valores'
 }
}
const purposeTitles={en:'Our Purpose',nl:'Ons doel',es:'Nuestro propósito'}
const values={
 en:['Authenticity','Wellbeing','Connection','Sustainability','Transformation','Integrity','Continuous Learning','Excellence'],
 nl:['Authenticiteit','Welzijn','Verbinding','Duurzaamheid','Transformatie','Integriteit','Blijven leren','Uitmuntendheid'],
 es:['Autenticidad','Bienestar','Conexión','Sostenibilidad','Transformación','Integridad','Aprendizaje continuo','Excelencia']
}
const About=({language})=>{const currentLanguage=copy[language]?language:'en';const t=copy[currentLanguage];return <div className="pt-20">
 <section className="py-20 bg-gradient-to-br from-pink-50 via-purple-50 to-blue-50 text-center"><h1 className="text-5xl md:text-6xl font-serif text-amber-700 mb-4">{t.title}</h1><p className="text-xl text-amber-700">{t.sub}</p></section>
 <section className="py-20 bg-white"><div className="max-w-5xl mx-auto px-4 space-y-14"><figure className="overflow-hidden rounded-2xl shadow-xl bg-amber-50"><img src={foundersPhoto} alt="Mieke van Lierop and Marcel Croes with their dog and a singing bowl in Aruba" loading="lazy" decoding="async" className="w-full aspect-[4/3] md:aspect-[16/9] object-cover object-center"/></figure><div className="grid md:grid-cols-2 gap-10"><Story title={t.openingTitle} text={t.opening}/><Story title={t.arubaTitle} text={t.aruba}/></div><div className="grid md:grid-cols-2 gap-8"><Person title={t.miekeTitle} text={t.mieke}/><Person title={t.marcelTitle} text={t.marcel}/></div><div className="grid lg:grid-cols-[0.9fr_1.1fr] gap-10 items-center"><Story title={t.togetherTitle} text={t.together}/><LearningGallery/></div><div className="max-w-3xl mx-auto"><Story title={t.smallTitle} text={t.small}/></div></div></section>
 <section className="py-16 bg-amber-50 text-center"><div className="max-w-4xl mx-auto px-4"><Heart className="h-9 w-9 text-amber-700 mx-auto mb-5"/><h2 className="text-4xl font-serif text-amber-700 mb-5">{purposeTitles[currentLanguage]}</h2><p className="text-xl text-gray-700 leading-relaxed">{t.purpose}</p></div></section>
 <section className="py-20 bg-white"><div className="max-w-6xl mx-auto px-4"><h2 className="text-4xl font-serif text-amber-700 text-center mb-10">{t.values}</h2><div className="grid sm:grid-cols-2 md:grid-cols-4 gap-5">{values[currentLanguage].map((v,i)=>{const Icon=[Heart,Leaf,Users,Sparkles][i%4];return <div key={v} className="border border-pink-100 rounded-xl p-5 text-center"><Icon className="h-6 w-6 text-amber-700 mx-auto mb-3"/><p className="font-medium text-gray-800">{v}</p></div>})}</div></div></section>
</div>}
const Story=({title,text})=><div><h2 className="text-3xl font-serif text-amber-700 mb-4">{title}</h2><p className="text-lg text-gray-700 leading-relaxed">{text}</p></div>
const Person=({title,text})=><div className="bg-gradient-to-br from-pink-50 to-amber-50 rounded-2xl p-8"><h2 className="text-3xl font-serif text-amber-700 mb-4">{title}</h2><p className="text-lg text-gray-700 leading-relaxed">{text}</p></div>
const LearningGallery=()=> <div className="grid grid-cols-[1.35fr_0.65fr] gap-3 md:gap-4 items-stretch">
 <figure className="overflow-hidden rounded-2xl shadow-lg bg-amber-50"><img src={egyptLearningPhoto} alt="Mieke and Marcel during a learning journey in Egypt" loading="lazy" decoding="async" className="w-full h-full min-h-72 object-cover object-center saturate-[.88] contrast-[.96] brightness-[1.02]"/></figure>
 <figure className="overflow-hidden rounded-2xl shadow-lg bg-amber-50"><img src={certificatePhoto} alt="Mieke and Marcel holding certificates from Het Inzicht" loading="lazy" decoding="async" className="w-full h-full min-h-72 object-cover object-[50%_38%] saturate-[.88] contrast-[.96] brightness-[1.02]"/></figure>
</div>
export default About
