import React from 'react'
import { Mail, Instagram, MessageCircle, Phone, Clock, Send } from 'lucide-react'
import { Button } from '@/components/ui/button'

const copy={
 en:{title:'Contact',sub:'Questions, bespoke experiences and personal guidance.',appointment:'By appointment only.',response:'We aim to respond to enquiries within 24 hours.',form:'Bookings and enquiries',formText:'For bookings, questions and personal guidance, please contact us directly via WhatsApp, email or personal contact.',home:'Home visits are available upon request and subject to location and availability.',booking:'An online booking system may be introduced in the future. Until then, all bookings are handled personally.',telephone:'Telephone',open:'Open WhatsApp',message:'Hello, I would like more information about the experiences offered by Key of Self Love.',emailSubject:'Key of Self Love enquiry'},
 nl:{title:'Contact',sub:'Voor vragen, maatwerkervaringen en persoonlijke begeleiding.',appointment:'Alleen op afspraak.',response:'We streven ernaar vragen binnen 24 uur te beantwoorden.',form:'Boekingen en vragen',formText:'Neem voor boekingen, vragen en persoonlijke begeleiding rechtstreeks contact met ons op via WhatsApp, e-mail of persoonlijk contact.',home:'Huisbezoeken zijn op aanvraag beschikbaar en afhankelijk van locatie en beschikbaarheid.',booking:'In de toekomst kan een online boekingssysteem worden geïntroduceerd. Tot die tijd behandelen we alle boekingen persoonlijk.',telephone:'Telefoon',open:'Open WhatsApp',message:'Hallo, ik wil graag meer informatie over de ervaringen van Key of Self Love.',emailSubject:'Vraag aan Key of Self Love'},
 es:{title:'Contacto',sub:'Preguntas, experiencias a medida y acompañamiento personal.',appointment:'Solo con cita previa.',response:'Nuestro objetivo es responder en un plazo de 24 horas.',form:'Reservas y consultas',formText:'Para reservas, preguntas y orientación personal, contáctanos directamente por WhatsApp, correo electrónico o contacto personal.',home:'Las visitas a domicilio están disponibles bajo solicitud, según ubicación y disponibilidad.',booking:'En el futuro se podrá introducir un sistema de reservas en línea. Hasta entonces, todas las reservas se gestionan personalmente.',telephone:'Teléfono',open:'Abrir WhatsApp',message:'Hola, me gustaría recibir más información sobre las experiencias que ofrece Key of Self Love.',emailSubject:'Consulta para Key of Self Love'}
}

const Contact=({language})=>{const t=copy[language]||copy.en;const wa=`https://wa.me/2975614808?text=${encodeURIComponent(t.message)}`;const email=`mailto:keyofselflove@gmail.com?subject=${encodeURIComponent(t.emailSubject)}`;return <div className="pt-20">
 <section className="py-20 bg-gradient-to-br from-pink-50 via-purple-50 to-blue-50 text-center"><h1 className="text-5xl font-serif text-amber-700 mb-4">{t.title}</h1><p className="text-xl text-gray-700">{t.sub}</p></section>
 <section className="py-20 bg-white"><div className="max-w-6xl mx-auto px-4 grid lg:grid-cols-2 gap-10"><div className="space-y-5">
  <a href={wa} target="_blank" rel="noreferrer" className="flex items-center gap-4 border rounded-xl p-5 hover:border-amber-400"><MessageCircle className="h-7 w-7 text-green-700"/><div><strong>WhatsApp Business</strong><p>+297 56 14 808</p></div></a>
  <a href="tel:+2975614808" className="flex items-center gap-4 border rounded-xl p-5 hover:border-amber-400"><Phone className="h-7 w-7 text-amber-700"/><div><strong>{t.telephone}</strong><p>+297 56 14 808</p></div></a>
  <a href={email} className="flex items-center gap-4 border rounded-xl p-5 hover:border-amber-400"><Mail className="h-7 w-7 text-amber-700"/><div><strong>Email</strong><p>keyofselflove@gmail.com</p></div></a>
  <a href="https://www.instagram.com/keyofselflove/" target="_blank" rel="noreferrer" className="flex items-center gap-4 border rounded-xl p-5 hover:border-amber-400"><Instagram className="h-7 w-7 text-pink-700"/><div><strong>Instagram</strong><p>@keyofselflove</p></div></a>
  <div className="flex items-start gap-4 bg-amber-50 rounded-xl p-5"><Clock className="h-6 w-6 text-amber-700 mt-1"/><div><strong>{t.appointment}</strong><p className="text-gray-600">{t.response}</p></div></div>
 </div><div className="border-2 border-dashed border-amber-200 rounded-xl p-8"><Send className="h-8 w-8 text-amber-700 mb-5"/><h2 className="text-3xl font-serif text-amber-700 mb-4">{t.form}</h2><p className="text-gray-700 mb-5">{t.formText}</p><p className="text-gray-600 mb-5">{t.booking}</p><p className="text-gray-600 mb-8">{t.home}</p><Button asChild className="bg-amber-700"><a href={wa} target="_blank" rel="noreferrer">{t.open}</a></Button></div></div></section>
</div>}
export default Contact
