import React from 'react'
import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Building2, Handshake, Hotel, Briefcase } from 'lucide-react'

const copy={
 en:{badge:'Partnerships in development',title:'Partner with Key of Self Love',sub:'Tailored wellness experiences designed around your guests, location and collaboration goals.',audiences:['Hotels & resorts','Retreat organisers','Travel advisors & concierge services','Villa managers & corporate wellness partners'],bespoke:'Bespoke by design',p1:'Hotel, group and bespoke programmes are available only after a partnership or written agreement is established. Programme structure, capacity, pricing, payment schedules and cancellation terms depend on the booking and any involved partners or suppliers.',p2:'Potential formats include private guest experiences, sound baths, sunrise or sunset sessions, couples experiences and special event programming. No unconfirmed partner is publicly named.',cta:'Partner enquiry'},
 nl:{badge:'Partnerships in ontwikkeling',title:'Werk samen met Key of Self Love',sub:'Wellnesservaringen op maat, afgestemd op uw gasten, locatie en samenwerkingsdoelen.',audiences:['Hotels & resorts','Retreatorganisatoren','Reisadviseurs & conciergediensten','Villamanagers & corporate-wellnesspartners'],bespoke:'Maatwerk als uitgangspunt',p1:'Hotel-, groeps- en maatwerkprogramma’s zijn alleen beschikbaar nadat een partnership of schriftelijke overeenkomst is gesloten. De programmaopbouw, capaciteit, prijs, betalingsregeling en annuleringsvoorwaarden hangen af van de boeking en eventuele betrokken partners of leveranciers.',p2:'Mogelijke vormen zijn privé-ervaringen voor gasten, sound baths, sessies bij zonsopkomst of zonsondergang, ervaringen voor stellen en programma’s voor speciale gelegenheden. Niet-bevestigde partners worden niet openbaar genoemd.',cta:'Partnership aanvragen'},
 es:{badge:'Colaboraciones en desarrollo',title:'Colabora con Key of Self Love',sub:'Experiencias de bienestar a medida, diseñadas en torno a sus huéspedes, su ubicación y sus objetivos de colaboración.',audiences:['Hoteles y resorts','Organizadores de retiros','Asesores de viaje y servicios de conserjería','Gestores de villas y socios de bienestar corporativo'],bespoke:'Diseñado a medida',p1:'Los programas para hoteles, grupos y experiencias a medida solo están disponibles después de establecer una colaboración o un acuerdo por escrito. La estructura, la capacidad, el precio, el calendario de pagos y las condiciones de cancelación dependen de la reserva y de los socios o proveedores implicados.',p2:'Los posibles formatos incluyen experiencias privadas para huéspedes, baños de sonido, sesiones al amanecer o al atardecer, experiencias para parejas y programas para ocasiones especiales. No se menciona públicamente a ningún socio que no esté confirmado.',cta:'Consulta para colaboradores'}
}

const Partners=({language})=>{const t=copy[language]||copy.en;return <div className="pt-20"><section className="py-20 bg-gradient-to-br from-pink-50 via-purple-50 to-blue-50 text-center"><span className="text-xs uppercase tracking-widest text-purple-700">{t.badge}</span><h1 className="text-5xl font-serif text-amber-700 my-4">{t.title}</h1><p className="text-xl text-gray-700 max-w-3xl mx-auto">{t.sub}</p></section><section className="py-20 bg-white"><div className="max-w-6xl mx-auto px-4"><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5 mb-12">{t.audiences.map((x,i)=>{const Icon=[Hotel,Handshake,Building2,Briefcase][i];return <div key={x} className="border rounded-xl p-6 text-center"><Icon className="h-8 w-8 text-amber-700 mx-auto mb-4"/><p className="font-medium">{x}</p></div>})}</div><div className="max-w-3xl mx-auto bg-amber-50 p-8 rounded-xl"><h2 className="text-3xl font-serif text-amber-700 mb-4">{t.bespoke}</h2><p className="text-gray-700 mb-4">{t.p1}</p><p className="text-gray-700 mb-7">{t.p2}</p><Button asChild variant="outline"><Link to="/contact">{t.cta}</Link></Button></div></div></section></div>}
export default Partners
