import React from 'react'

const copy={
 en:{
  title:'Guest Information & Policies',sub:'Clear information for a safe and well-prepared experience.',
  sections:[
   {title:'Prices & payments',p:['All prices are in USD and include taxes and service charges unless stated otherwise.','Accepted methods: PayPal, bank transfer and cash (USD or AWG).']},
   {title:'Resonance Experience Collection',p:['Full payment is required upon booking. Free cancellation is available up to 24 hours before the scheduled start. No-shows are non-refundable.','Programmes involving snorkeling require guests to be comfortable in the water and able to follow the guide’s instructions. Flotation devices may be provided when appropriate.']},
   {title:'Resonance Healing Journey',p:['A 50% deposit confirms the booking. The remaining balance is due 48 hours before the session.','Cancellations or rescheduling requests made at least 24 hours before the session qualify for a full refund of the deposit or a move to another available date. Within 24 hours, the deposit is non-refundable. No-shows are non-refundable.','Exceptions may be considered at the discretion of Key of Self Love for exceptional circumstances such as medical emergencies or major travel disruptions.']},
   {title:'Retreats',p:['A 30% non-refundable deposit confirms a retreat place. Final payment is due 30 days before arrival.'],list:['More than 60 days before arrival: refund of payments excluding the deposit.','Between 30 and 60 days: 50% refund excluding the deposit.','Within 30 days: non-refundable.'],after:['If a place can be resold, Key of Self Love may offer an additional refund minus administrative costs.','If Key of Self Love cancels, participants may choose a full refund, transfer to a future retreat, or credit toward another experience. Key of Self Love is not responsible for flights, accommodation or other travel-related expenses.','Retreats require at least 6 and accept no more than 10 participants.']},
   {title:'Weather & programme changes',p:['Key of Self Love may cancel, postpone or adapt an experience because of weather, sea conditions or other safety concerns. If Key of Self Love cancels due to unsafe conditions, guests may reschedule or receive a full refund.','Routes and locations vary by programme. The exact meeting location is shared after booking.']},
   {title:'Age & water safety',p:['The minimum participation age is 6. Guests under 16 must be accompanied by a parent or legal guardian.','Guests do not need to be strong swimmers but must be comfortable in the water. Anyone unable to swim or anxious in water must inform the guides before participating. Participation is voluntary and at the guest’s own risk.']},
   {title:'Health & informed consent',p:['Guests must share relevant medical or psychological information before participation when requested. This may include heart conditions, severe asthma, epilepsy, recent surgery, mobility limitations, pregnancy-related concerns, severe sound sensitivity, severe psychiatric conditions or relevant implanted electronic medical devices.','A programme may be adapted or declined where participation could present a risk. Guests may pause or stop a session at any time.','Required consent is collected during booking. Certain experiences may also require an intake form. In an emergency, local emergency services will be contacted.']},
   {title:'Liability & belongings',p:['Participation is voluntary. Guests are responsible for disclosing relevant information and following guide instructions. Key of Self Love is not responsible for personal belongings that are lost, stolen or damaged during participation.']},
   {title:'Privacy, photographs & reviews',p:['Personal information is used only for communication, booking and service delivery. It is not sold and is shared only where required for a booking or by law. Guests may request access, correction or deletion.','Photos, videos, names and identifying details are used only with explicit permission. Only genuine testimonials with written permission are published. Individual experiences and results may vary.']},
   {title:'Groups, hotels & bespoke bookings',p:['Hotel partnerships, group bookings and bespoke experiences may have separate written agreements, payment schedules and cancellation terms depending on the booking and involved partners or suppliers.']}
  ]
 },
 nl:{
  title:'Gastinformatie & voorwaarden',sub:'Duidelijke informatie voor een veilige en goed voorbereide ervaring.',
  sections:[
   {title:'Prijzen & betalingen',p:['Alle prijzen zijn in USD en inclusief belastingen en servicekosten, tenzij anders vermeld.','Geaccepteerde betaalmethoden: PayPal, bankoverschrijving en contant (USD of AWG).']},
   {title:'Resonance Experience Collection',p:['Volledige betaling is vereist bij de boeking. Kosteloos annuleren kan tot 24 uur vóór de geplande start. Bij niet verschijnen vindt geen terugbetaling plaats.','Voor programma’s met snorkelen moeten gasten zich comfortabel voelen in het water en de aanwijzingen van de gids kunnen opvolgen. Waar passend kunnen drijfmiddelen worden verstrekt.']},
   {title:'Resonance Healing Journey',p:['Een aanbetaling van 50% bevestigt de boeking. Het resterende bedrag moet 48 uur vóór de sessie zijn voldaan.','Bij annuleren of verplaatsen ten minste 24 uur vóór de sessie kan de gast kiezen voor volledige terugbetaling van de aanbetaling of een nieuwe beschikbare datum. Binnen 24 uur is de aanbetaling niet-restitueerbaar. Bij niet verschijnen vindt geen terugbetaling plaats.','Key of Self Love kan naar eigen inzicht een uitzondering overwegen bij bijzondere omstandigheden, zoals een medisch noodgeval of ernstige reisverstoring.']},
   {title:'Retreats',p:['Een niet-restitueerbare aanbetaling van 30% bevestigt een retreatplaats. De eindbetaling is 30 dagen vóór aankomst verschuldigd.'],list:['Meer dan 60 dagen vóór aankomst: terugbetaling van alle betalingen, exclusief de aanbetaling.','Tussen 30 en 60 dagen: 50% terugbetaling, exclusief de aanbetaling.','Binnen 30 dagen: geen terugbetaling.'],after:['Als de plaats opnieuw kan worden verkocht, kan Key of Self Love een aanvullende terugbetaling aanbieden na aftrek van administratiekosten.','Als Key of Self Love annuleert, kunnen deelnemers kiezen voor volledige terugbetaling, verplaatsing naar een toekomstige retreatdatum of een tegoed voor een andere ervaring. Key of Self Love is niet verantwoordelijk voor vluchten, accommodatie of andere reisgerelateerde kosten.','Retreats vereisen minimaal 6 en hebben maximaal 10 deelnemers.']},
   {title:'Weer & programmawijzigingen',p:['Key of Self Love kan een ervaring annuleren, uitstellen of aanpassen vanwege het weer, de toestand van de zee of andere veiligheidsredenen. Als Key of Self Love vanwege onveilige omstandigheden annuleert, kunnen gasten verplaatsen of een volledige terugbetaling ontvangen.','Routes en locaties verschillen per programma. De exacte ontmoetingslocatie wordt na de boeking gedeeld.']},
   {title:'Leeftijd & veiligheid in het water',p:['De minimumleeftijd voor deelname is 6 jaar. Gasten jonger dan 16 jaar moeten worden begeleid door een ouder of wettelijke voogd.','Gasten hoeven geen sterke zwemmers te zijn, maar moeten zich wel comfortabel voelen in het water. Wie niet kan zwemmen of angstig is in het water, moet dit vóór deelname aan de gidsen melden. Deelname is vrijwillig en op eigen risico.']},
   {title:'Gezondheid & geïnformeerde toestemming',p:['Gasten moeten op verzoek vóór deelname relevante medische of psychologische informatie delen. Dit kan onder meer gaan om hartaandoeningen, ernstige astma, epilepsie, recente operaties, mobiliteitsbeperkingen, zwangerschapsgerelateerde zorgen, ernstige geluidsgevoeligheid, ernstige psychiatrische aandoeningen of relevante geïmplanteerde elektronische medische apparaten.','Een programma kan worden aangepast of geweigerd wanneer deelname een risico kan vormen. Gasten mogen een sessie op ieder moment pauzeren of stoppen.','De vereiste toestemming wordt tijdens de boeking vastgelegd. Voor bepaalde ervaringen kan ook een intakeformulier nodig zijn. In een noodgeval worden de lokale hulpdiensten ingeschakeld.']},
   {title:'Aansprakelijkheid & persoonlijke eigendommen',p:['Deelname is vrijwillig. Gasten zijn verantwoordelijk voor het delen van relevante informatie en het opvolgen van aanwijzingen van de gids. Key of Self Love is niet verantwoordelijk voor persoonlijke eigendommen die tijdens deelname verloren, gestolen of beschadigd raken.']},
   {title:'Privacy, foto’s & reviews',p:['Persoonsgegevens worden uitsluitend gebruikt voor communicatie, boekingen en dienstverlening. Ze worden niet verkocht en alleen gedeeld wanneer dit voor een boeking of wettelijk vereist is. Gasten kunnen inzage, correctie of verwijdering aanvragen.','Foto’s, video’s, namen en herkenbare gegevens worden alleen met expliciete toestemming gebruikt. Alleen echte testimonials met schriftelijke toestemming worden gepubliceerd. Individuele ervaringen en resultaten kunnen verschillen.']},
   {title:'Groepen, hotels & maatwerkboekingen',p:['Hotelpartnerships, groepsboekingen en maatwerkervaringen kunnen afzonderlijke schriftelijke overeenkomsten, betalingsregelingen en annuleringsvoorwaarden hebben, afhankelijk van de boeking en betrokken partners of leveranciers.']}
  ]
 },
 es:{
  title:'Información y políticas para huéspedes',sub:'Información clara para una experiencia segura y bien preparada.',
  sections:[
   {title:'Precios y pagos',p:['Todos los precios se indican en USD e incluyen impuestos y cargos por servicio, salvo que se indique lo contrario.','Métodos aceptados: PayPal, transferencia bancaria y efectivo (USD o AWG).']},
   {title:'Resonance Experience Collection',p:['Se requiere el pago completo al reservar. La cancelación es gratuita hasta 24 horas antes del inicio programado. Las ausencias no son reembolsables.','En los programas que incluyen esnórquel, los huéspedes deben sentirse cómodos en el agua y poder seguir las instrucciones del guía. Se pueden proporcionar dispositivos de flotación cuando corresponda.']},
   {title:'Resonance Healing Journey',p:['Un depósito del 50% confirma la reserva. El saldo restante debe pagarse 48 horas antes de la sesión.','Las solicitudes de cancelación o cambio realizadas al menos 24 horas antes de la sesión permiten elegir entre el reembolso completo del depósito o una nueva fecha disponible. Dentro de las 24 horas, el depósito no es reembolsable. Las ausencias no son reembolsables.','Key of Self Love puede considerar excepciones, a su discreción, en circunstancias extraordinarias como emergencias médicas o alteraciones importantes del viaje.']},
   {title:'Retiros',p:['Un depósito no reembolsable del 30% confirma la plaza en un retiro. El pago final debe realizarse 30 días antes de la llegada.'],list:['Más de 60 días antes de la llegada: reembolso de los pagos, excepto el depósito.','Entre 30 y 60 días: reembolso del 50%, excepto el depósito.','Dentro de los 30 días: no reembolsable.'],after:['Si la plaza puede venderse de nuevo, Key of Self Love puede ofrecer un reembolso adicional menos los gastos administrativos.','Si Key of Self Love cancela, los participantes pueden elegir entre un reembolso completo, trasladar su reserva a un retiro futuro o recibir crédito para otra experiencia. Key of Self Love no se responsabiliza de vuelos, alojamiento ni otros gastos relacionados con el viaje.','Los retiros requieren un mínimo de 6 y aceptan un máximo de 10 participantes.']},
   {title:'Clima y cambios de programa',p:['Key of Self Love puede cancelar, posponer o adaptar una experiencia por el clima, las condiciones del mar u otros motivos de seguridad. Si Key of Self Love cancela por condiciones inseguras, los huéspedes pueden cambiar la fecha o recibir un reembolso completo.','Las rutas y ubicaciones varían según el programa. El punto de encuentro exacto se comparte después de la reserva.']},
   {title:'Edad y seguridad en el agua',p:['La edad mínima para participar es de 6 años. Los huéspedes menores de 16 años deben estar acompañados por uno de sus padres o su tutor legal.','No es necesario ser un nadador experto, pero los huéspedes deben sentirse cómodos en el agua. Quien no sepa nadar o sienta ansiedad en el agua debe informar a los guías antes de participar. La participación es voluntaria y bajo la responsabilidad del huésped.']},
   {title:'Salud y consentimiento informado',p:['Cuando se solicite, los huéspedes deben comunicar antes de participar cualquier información médica o psicológica relevante. Esto puede incluir afecciones cardíacas, asma grave, epilepsia, cirugía reciente, limitaciones de movilidad, inquietudes relacionadas con el embarazo, sensibilidad grave al sonido, trastornos psiquiátricos graves o dispositivos médicos electrónicos implantados relevantes.','Un programa puede adaptarse o rechazarse si la participación pudiera suponer un riesgo. Los huéspedes pueden pausar o detener una sesión en cualquier momento.','El consentimiento requerido se recoge durante la reserva. Algunas experiencias también pueden requerir un formulario de admisión. En caso de emergencia se contactará con los servicios locales de emergencia.']},
   {title:'Responsabilidad y pertenencias',p:['La participación es voluntaria. Los huéspedes son responsables de comunicar la información relevante y seguir las instrucciones del guía. Key of Self Love no se responsabiliza por objetos personales perdidos, robados o dañados durante la participación.']},
   {title:'Privacidad, fotografías y reseñas',p:['La información personal se utiliza únicamente para la comunicación, las reservas y la prestación del servicio. No se vende y solo se comparte cuando sea necesario para una reserva o por obligación legal. Los huéspedes pueden solicitar acceso, corrección o eliminación.','Las fotos, los vídeos, los nombres y los datos identificativos solo se utilizan con permiso explícito. Únicamente se publican testimonios auténticos con autorización escrita. Las experiencias y los resultados individuales pueden variar.']},
   {title:'Grupos, hoteles y reservas a medida',p:['Las colaboraciones con hoteles, las reservas de grupos y las experiencias a medida pueden tener acuerdos escritos, calendarios de pago y condiciones de cancelación independientes, según la reserva y los socios o proveedores implicados.']}
  ]
 }
}

const Section=({section})=><section className="border-b border-pink-100 pb-8"><h2 className="text-3xl font-serif text-amber-700 mb-4">{section.title}</h2><div className="space-y-3 text-gray-700 leading-relaxed">{section.p?.map((p,i)=><p key={`p-${i}`}>{p}</p>)}{section.list&&<ul className="list-disc pl-6 space-y-2">{section.list.map((item,i)=><li key={i}>{item}</li>)}</ul>}{section.after?.map((p,i)=><p key={`a-${i}`}>{p}</p>)}</div></section>
const Policies=({language})=>{const t=copy[language]||copy.en;return <div className="pt-20"><section className="py-20 bg-gradient-to-br from-pink-50 via-purple-50 to-blue-50 text-center"><h1 className="text-5xl font-serif text-amber-700 mb-4">{t.title}</h1><p className="text-xl text-gray-700">{t.sub}</p></section><main className="max-w-4xl mx-auto px-4 py-16 space-y-10">{t.sections.map(section=><Section key={section.title} section={section}/>)}</main></div>}
export default Policies
