import React from 'react'

const Section=({title,children})=><section className="border-b border-pink-100 pb-8"><h2 className="text-3xl font-serif text-amber-700 mb-4">{title}</h2><div className="space-y-3 text-gray-700 leading-relaxed">{children}</div></section>
const Policies=()=> <div className="pt-20"><section className="py-20 bg-gradient-to-br from-pink-50 via-purple-50 to-blue-50 text-center"><h1 className="text-5xl font-serif text-amber-700 mb-4">Guest Information & Policies</h1><p className="text-xl text-gray-700">Clear information for a safe and well-prepared experience.</p></section><main className="max-w-4xl mx-auto px-4 py-16 space-y-10">
  <Section title="Prices & payments"><p>All prices are in USD and include taxes and service charges unless stated otherwise.</p><p>Accepted methods: bank transfer, Wise, cash, credit card and PayPal.</p></Section>
  <Section title="The Resonance Experience Collection"><p>Full payment is required upon booking. Free cancellation is available up to 24 hours before the scheduled start. No-shows are non-refundable.</p><p>Programmes involving snorkeling require guests to be comfortable in the water and able to follow the guide’s instructions. Flotation devices may be provided when appropriate.</p></Section>
  <Section title="Resonance Healing Journey"><p>A 50% deposit confirms the booking. The remaining balance is due 48 hours before the session.</p><p>Cancellations or rescheduling requests made at least 24 hours before the session qualify for a full refund of the deposit or a move to another available date. Within 24 hours, the deposit is non-refundable. No-shows are non-refundable.</p><p>Exceptions may be considered at the discretion of Key of Self Love for exceptional circumstances such as medical emergencies or major travel disruptions.</p></Section>
  <Section title="Retreats"><p>A 30% non-refundable deposit confirms a retreat place. Final payment is due 30 days before arrival.</p><ul className="list-disc pl-6 space-y-2"><li>More than 60 days before arrival: refund of payments excluding the deposit.</li><li>Between 30 and 60 days: 50% refund excluding the deposit.</li><li>Within 30 days: non-refundable.</li></ul><p>If a place can be resold, Key of Self Love may offer an additional refund minus administrative costs.</p><p>If Key of Self Love cancels, participants may choose a full refund, transfer to a future retreat, or credit toward another experience. Key of Self Love is not responsible for flights, accommodation or other travel-related expenses.</p><p>Retreats require at least 6 and accept no more than 10 participants.</p></Section>
  <Section title="Weather & programme changes"><p>Key of Self Love may cancel, postpone or adapt an experience because of weather, sea conditions or other safety concerns. If Key of Self Love cancels due to unsafe conditions, guests may reschedule or receive a full refund.</p><p>Routes and locations vary by programme. The exact meeting location is shared after booking.</p></Section>
  <Section title="Age & water safety"><p>The minimum participation age is 6. Guests under 16 must be accompanied by a parent or legal guardian.</p><p>Guests do not need to be strong swimmers but must be comfortable in the water. Anyone unable to swim or anxious in water must inform the guides before participating. Participation is voluntary and at the guest’s own risk.</p></Section>
  <Section title="Health & informed consent"><p>Guests must share relevant medical or psychological information before participation when requested. This may include heart conditions, severe asthma, epilepsy, recent surgery, mobility limitations, pregnancy-related concerns, severe sound sensitivity, severe psychiatric conditions or relevant implanted electronic medical devices.</p><p>A programme may be adapted or declined where participation could present a risk. Guests may pause or stop a session at any time.</p><p>Required consent is collected during booking. Certain experiences may also require an intake form. In an emergency, local emergency services will be contacted.</p></Section>
  <Section title="Liability & belongings"><p>Participation is voluntary. Guests are responsible for disclosing relevant information and following guide instructions. Key of Self Love is not responsible for personal belongings that are lost, stolen or damaged during participation.</p></Section>
  <Section title="Privacy, photographs & reviews"><p>Personal information is used only for communication, booking and service delivery. It is not sold and is shared only where required for a booking or by law. Guests may request access, correction or deletion.</p><p>Photos, videos, names and identifying details are used only with explicit permission. Only genuine testimonials with written permission are published. Individual experiences and results may vary.</p></Section>
  <Section title="Groups, hotels & bespoke bookings"><p>Hotel partnerships, group bookings and bespoke experiences may have separate written agreements, payment schedules and cancellation terms depending on the booking and involved partners or suppliers.</p></Section>
</main></div>
export default Policies
