import React from 'react'
import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Clock, MapPin, Check, MessageCircle } from 'lucide-react'
import turtlePhoto from '../assets/experience-turtle.jpg'
import sunsetPhoto from '../assets/experience-sunset.jpg'
import naturePhoto from '../assets/experience-nature.jpg'
import soundBowlPhoto from '../assets/experience-sound-bowl.jpg'
import beachPhoto from '../assets/experience-beach.jpg'
import rayPhoto from '../assets/experience-ray.jpg'
import couplesPhoto from '../assets/experience-couples.jpg'

const labels={
 en:{title:'Experiences',sub:'Current offerings and experiences being developed with care.',available:'Available by appointment',coming:'Coming Soon',development:'In Development',included:'All listed prices include taxes and service charges unless stated otherwise.',location:'The exact location depends on the programme and is shared after booking.',question:'Questions about an experience?',ask:'Ask on WhatsApp',interest:'Contact us for future retreat updates'},
 nl:{title:'Ervaringen',sub:'Huidig aanbod en ervaringen die zorgvuldig worden ontwikkeld.',available:'Beschikbaar op afspraak',coming:'Binnenkort',development:'In ontwikkeling',included:'Alle genoemde prijzen zijn inclusief belastingen en servicekosten, tenzij anders vermeld.',location:'De exacte locatie hangt af van het programma en wordt na boeking gedeeld.',question:'Vragen over een ervaring?',ask:'Vraag het via WhatsApp',interest:'Neem contact op voor toekomstige retreatupdates'},
 es:{title:'Experiencias',sub:'Oferta actual y experiencias que se desarrollan cuidadosamente.',available:'Disponible con cita previa',coming:'Próximamente',development:'En desarrollo',included:'Todos los precios incluyen impuestos y cargos de servicio salvo indicación contraria.',location:'La ubicación exacta depende del programa y se comparte después de reservar.',question:'¿Preguntas sobre una experiencia?',ask:'Pregunta por WhatsApp',interest:'Contáctanos para recibir novedades sobre retiros'}
}

const items=[
 {status:'available',name:'Resonance Healing Journey',price:'USD 195',duration:'2–3 hours',text:'A private, one-to-one experience for guests who value personal attention and a calm setting. Sound, resonance, coaching and guided integration are brought together in a programme adapted to the individual.',features:['Personalised guidance','Sound and resonance','Time for reflection and integration','Available by appointment'],note:'Transport is optional and can be added on request.',image:soundBowlPhoto,imagePosition:'center 52%'},
 {status:'available',name:'Sound Bath Experience',price:'USD 65 per person',duration:'Group experience',text:'A small-group sound and resonance experience for people who want to slow down and experience sound in a welcoming shared setting.',features:['Small-group setting','Maximum 8 participants at the current location','Available by appointment','Hosted in the garden unless another location is arranged'],image:sunsetPhoto,imagePosition:'center'},
 {status:'available',name:'The Resonance Experience',price:'USD 395 per person',duration:'Half day',text:'A private half-day journey rooted in Aruba. The programme brings together sound and resonance, nature, mindful nourishment, coaching and guided reflection. Ocean immersion or snorkeling may be included when suited to the programme and conditions.',features:['Programme, equipment, nourishment and refreshments included','Transport included','A changing route and location selected for the programme','For individuals, couples or a private small group'],note:'Minimum age 6. Guests under 16 must be accompanied by a parent or legal guardian.',image:turtlePhoto,imagePosition:'center 42%'},
 {status:'development',name:'Couples Resonance Experience',price:'USD 555 per couple',duration:'Programme in development',text:'A private experience for two people who want to step away from daily routines and spend meaningful time together through sound, presence, nature and shared reflection.',features:['Introductory total price','Personal and private format','Snorkeling may be included as part of the programme','Not yet bookable'],image:couplesPhoto,imagePosition:'center 58%'},
 {status:'coming',name:'Transformational Workshops',price:'Starting from USD 595 per person',duration:'Programme dependent',text:'Small-group workshops exploring themes such as sound, resonance, self-awareness and conscious living. Content, duration, materials and location will vary by workshop.',features:['Materials included','Minimum 4 participants','Maximum 8 at the current home location','Up to 12 at a suitable larger venue'],image:naturePhoto,imagePosition:'center 70%'},
 {status:'coming',name:'Transformational Retreats',price:null,duration:'Multiple formats in development',text:'Intentionally small retreat experiences in Aruba, bringing together sound and resonance, nature, ocean experiences, conscious living, personal development and meaningful connection. The first planned format is a three-day pilot retreat.',features:['Coming Soon','Minimum 6 participants','Maximum 10 participants','Not yet bookable'],interest:true,image:beachPhoto,imagePosition:'center 62%'},
 {status:'coming',name:'Private Group Experiences',price:'Custom quotation',duration:'Tailored',text:'Bespoke small-group experiences shaped around the occasion, location and needs of the group. The programme may bring together sound, nature, reflection and shared time.',features:['Programme-dependent capacity','Transport included where applicable','Location selected to suit the programme','Not yet bookable'],image:rayPhoto,imagePosition:'center 48%'}
]

const Services=({language})=>{const t=labels[language]||labels.en;const wa='https://wa.me/2975614808?text=Hello%2C%20I%20would%20like%20more%20information%20about%20the%20experiences%20offered%20by%20Key%20of%20Self%20Love.';return <div className="pt-20">
 <section className="py-20 bg-gradient-to-br from-pink-50 via-purple-50 to-blue-50 text-center"><h1 className="text-5xl md:text-6xl font-serif text-amber-700 mb-4">{t.title}</h1><p className="text-xl text-gray-700">{t.sub}</p></section>
 <section className="py-16 bg-white"><div className="max-w-7xl mx-auto px-4"><p className="text-center text-gray-600 mb-10">{t.included}</p><div className="grid md:grid-cols-2 gap-7">{items.map(x=><Card key={x.name} className="relative overflow-hidden border-2 border-pink-100">{x.image&&<><img src={x.image} alt="" aria-hidden="true" className="absolute inset-0 w-full h-full object-cover saturate-[.78] contrast-[.94] brightness-[1.06]" style={{objectPosition:x.imagePosition}}/><div className="absolute inset-0 bg-[rgba(255,253,248,.86)]"/></>}<CardHeader className="relative z-10"><div className="flex justify-between gap-4"><div><span className={`text-xs uppercase tracking-widest ${x.status==='available'?'text-green-700':'text-purple-700'}`}>{t[x.status]}</span><CardTitle className="text-2xl text-amber-700 mt-2">{x.name}</CardTitle></div>{x.price&&<div className="font-semibold text-right">{x.price}</div>}</div></CardHeader><CardContent className="relative z-10"><p className="text-gray-700 mb-5">{x.text}</p><div className="flex items-center text-sm text-gray-600 mb-4"><Clock className="h-4 w-4 mr-2"/>{x.duration}</div><ul className="space-y-2 mb-4">{x.features.map(f=><li key={f} className="flex text-sm text-gray-700"><Check className="h-4 w-4 text-amber-700 mr-2 mt-0.5 shrink-0"/>{f}</li>)}</ul>{x.note&&<p className="text-sm text-gray-600">{x.note}</p>}{x.status==='available'?<Button asChild className="mt-6 bg-amber-700"><a href={wa} target="_blank" rel="noreferrer"><MessageCircle className="h-4 w-4 mr-2"/>{t.ask}</a></Button>:x.interest?<Button asChild variant="outline" className="mt-6"><Link to="/contact">{t.interest}</Link></Button>:<div className="mt-6 text-sm font-medium text-purple-700">{t[x.status]} — not yet bookable</div>}</CardContent></Card>)}</div><div className="mt-10 flex items-start gap-3 text-gray-600"><MapPin className="h-5 w-5 text-amber-700 shrink-0"/><p>{t.location}</p></div></div></section>
 <section className="py-14 bg-amber-50 text-center"><h2 className="text-3xl font-serif text-amber-700 mb-5">{t.question}</h2><Button asChild variant="outline"><Link to="/contact">Contact Key of Self Love</Link></Button></section>
</div>}
export default Services
