import React from 'react'
import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Quote, ShieldCheck } from 'lucide-react'

const copy={
 en:{title:'Guest Voices',sub:'Real experiences, shared with permission.',empty:'We are preparing this space for verified guest reviews. We only publish genuine testimonials with written permission, and never present an individual experience as a guaranteed result.',privacy:'Guests choose how they are identified: by first name, location, full name, photo or anonymously. Personal details and photographs are never published without explicit consent.',disclaimer:'Individual experiences and results may vary.',cta:'Share Your Experience'},
 nl:{title:'Ervaringen van gasten',sub:'Echte ervaringen, gedeeld met toestemming.',empty:'We bereiden deze ruimte voor op geverifieerde reviews. We publiceren uitsluitend echte testimonials met schriftelijke toestemming en presenteren een persoonlijke ervaring nooit als gegarandeerd resultaat.',privacy:'Gasten kiezen zelf hoe zij worden vermeld: voornaam, locatie, volledige naam, foto of anoniem. Persoonsgegevens en foto’s worden nooit zonder expliciete toestemming gepubliceerd.',disclaimer:'Individuele ervaringen en resultaten kunnen verschillen.',cta:'Deel jouw ervaring'},
 es:{title:'Voces de nuestros huéspedes',sub:'Experiencias reales, compartidas con permiso.',empty:'Estamos preparando este espacio para reseñas verificadas. Solo publicamos testimonios auténticos con permiso escrito y nunca presentamos una experiencia individual como resultado garantizado.',privacy:'Cada huésped elige cómo desea aparecer. Nunca publicamos datos personales o fotografías sin consentimiento explícito.',disclaimer:'Las experiencias y los resultados individuales pueden variar.',cta:'Comparte tu experiencia'}
}

const Testimonials=({language})=>{const t=copy[language]||copy.en;return <div className="pt-20"><section className="py-20 bg-gradient-to-br from-pink-50 via-purple-50 to-blue-50 text-center"><Quote className="h-10 w-10 text-amber-700 mx-auto mb-5"/><h1 className="text-5xl font-serif text-amber-700 mb-4">{t.title}</h1><p className="text-xl text-gray-700">{t.sub}</p></section><section className="py-24 bg-white"><div className="max-w-3xl mx-auto px-4 text-center"><ShieldCheck className="h-12 w-12 text-green-700 mx-auto mb-6"/><p className="text-xl text-gray-700 leading-relaxed mb-6">{t.empty}</p><p className="text-gray-600 mb-10">{t.privacy}</p><p className="text-sm text-gray-500 mb-8">{t.disclaimer}</p><Button asChild variant="outline"><Link to="/share-your-experience">{t.cta}</Link></Button></div></section></div>}
export default Testimonials
